export const pagesRoutes = [
  ["v-184f4da6","/intro.html",{"c":["introduction"],"v":"/assets/imgs/bgs/4.png","e":"<h1> 介绍页</h1>\n<p>将你的个人介绍和档案放置在此处。</p>\n","y":"a","t":"介绍页","i":"circle-info"},["/intro","/intro.md"]],
  ["v-8daa1a0e","/",{"y":"h","t":"HOME","i":"home"},["/index.html","/README.md"]],
  ["v-e20cf1ac","/posts/diary/20230609.html",{"a":"neonscape","d":1686268800000,"l":"2023年6月9日","c":["diary"],"v":"/assets/imgs/bgs/2.jpg","e":"<h2> this is a test</h2>\n","y":"a","t":""},["/posts/diary/20230609","/posts/diary/20230609.md"]],
  ["v-46119451","/posts/diary/catalogue.html",{"y":"p","t":"My Diarys","i":"compass","I":0},["/posts/diary/catalogue","/posts/diary/catalogue.md"]],
  ["v-3706649a","/404.html",{"y":"p","t":""},["/404"]],
  ["v-0da95c01","/posts/diary/",{"y":"p","t":"Diary"},["/posts/diary/index.html"]],
  ["v-e1e3da16","/posts/",{"y":"p","t":"Posts"},["/posts/index.html"]],
  ["v-5bc93818","/category/",{"y":"p","t":"分类"},["/category/index.html"]],
  ["v-744d024e","/tag/",{"y":"p","t":"标签"},["/tag/index.html"]],
  ["v-e52c881c","/article/",{"y":"p","t":"文章"},["/article/index.html"]],
  ["v-154dc4c4","/star/",{"y":"p","t":"收藏"},["/star/index.html"]],
  ["v-01560935","/timeline/",{"y":"p","t":"时间轴"},["/timeline/index.html"]],
  ["v-bef94b86","/category/introduction/",{"y":"p","t":"introduction 分类"},["/category/introduction/index.html"]],
  ["v-b7a24a38","/category/diary/",{"y":"p","t":"diary 分类"},["/category/diary/index.html"]],
]
